#!/bin/bash

# Manual deployment steps for Bio Guard Bot

echo "🚀 Manual Bio Guard Bot Deployment"
echo "==================================="

# Server details
SERVER="root@140.245.240.202"
PORT="22"
REMOTE_DIR="/opt/bio_guard_bot"

echo "Please follow these steps manually:"
echo ""
echo "1. Connect to your server:"
echo "   ssh -p $PORT $SERVER"
echo ""
echo "2. Once connected, run these commands on the server:"
echo ""
echo "   # Create directory"
echo "   mkdir -p $REMOTE_DIR"
echo ""
echo "   # Install system dependencies"
echo "   apt update"
echo "   apt install -y python3 python3-pip python3-venv sqlite3"
echo ""
echo "   # Create virtual environment"
echo "   cd $REMOTE_DIR"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate"
echo ""
echo "3. On your local machine, transfer files:"
echo "   scp -P $PORT '/Users/nishkarshkr/Desktop/bio link/bio_guard_bot.py' $SERVER:$REMOTE_DIR/"
echo "   scp -P $PORT '/Users/nishkarshkr/Desktop/bio link/requirements.txt' $SERVER:$REMOTE_DIR/"
echo "   scp -P $PORT '/Users/nishkarshkr/Desktop/bio link/.env' $SERVER:$REMOTE_DIR/"
echo ""
echo "4. Back on the server, continue with:"
echo "   # Install Python dependencies"
echo "   cd $REMOTE_DIR"
echo "   source venv/bin/activate"
echo "   pip install --upgrade pip"
echo "   pip install -r requirements.txt"
echo ""
echo "   # Set permissions"
echo "   chmod 600 .env"
echo "   chmod 755 bio_guard_bot.py"
echo ""
echo "5. Create systemd service file:"
echo "   sudo nano /etc/systemd/system/bio-guard-bot.service"
echo ""
echo "   # Add this content:"
echo "   [Unit]"
echo "   Description=Bio Guard Telegram Bot"
echo "   After=network.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=root"
echo "   WorkingDirectory=$REMOTE_DIR"
echo "   Environment=PATH=$REMOTE_DIR/venv/bin"
echo "   ExecStart=$REMOTE_DIR/venv/bin/python bio_guard_bot.py"
echo "   Restart=always"
echo "   RestartSec=10"
echo "   StandardOutput=journal"
echo "   StandardError=journal"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo ""
echo "6. Enable and start the service:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable bio-guard-bot.service"
echo "   sudo systemctl start bio-guard-bot.service"
echo ""
echo "7. Check status:"
echo "   sudo systemctl status bio-guard-bot.service"
echo ""
echo "8. View logs:"
echo "   journalctl -u bio-guard-bot -f"